.TH TICKIT_TERM_NEW 3
.SH NAME
tickit_term_new \- create a new terminal instance
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "TickitTerm *tickit_term_new(void);"
.BI "TickitTerm *tickit_term_new_for_termtype(const char *" termtype );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
These functions are now discouraged. Applications should use \fBtickit_term_build\fP(3) instead.
.SH "SEE ALSO"
.BR tickit_term_build (3),
.BR tickit_term (7),
.BR tickit (7)
