.TH TICKIT_RECTSET_CONTAINS 3
.SH NAME
tickit_rectset_contains \- test if an area is contained by a rectangle set
.SH SYNOPSIS
.nf
.B #include <tickit.h>
.sp
.BI "bool tickit_rectset_contains(const TickitRectSet *" trs ", const TickitRect *" rect );
.fi
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_rectset_contains\fP() tests whether the area given by \fIrect\fP is entirely contained by one or more regions in the rectangle set.
.SH "RETURN VALUE"
\fBtickit_rectset_contains\fP() returns a true value if the given area is entirely covered by one or more regions, or false if at least some portion of it remains uncovered.
.SH "SEE ALSO"
.BR tickit_rectset_new (3),
.BR tickit_rectset (7),
.BR tickit_rect (7),
.BR tickit (7)
