.TH TICKIT_TERM_ERASECH 3
.SH NAME
tickit_term_erasech \- erase characters from the terminal
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "void tickit_term_erasech(TickitTerm *" tt ", int " count ", TickitMaybeBool " moveend );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_term_erasech\fP() erases \fIcount\fP character cells forward from the current cursor location, using the current pen background colour.
.PP
Some terminals cannot erase using the background colour, so this operation may be implemented by printing spaces on such terminals. This will move the cursor to the end of the erased region. Other terminals that do erase with background colour can be erased without moving the cursor. The \fImoveend\fP parameter controls the behaviour of the cursor location when this function returns. If set to \fBTICKIT_YES\fP, the cursor will be moved to the end of the erased region if required. If set to \fBTICKIT_NO\fP, the cursor will be moved back to its original location if required. If set to \fBTICKIT_MAYBE\fP, this function will take whichever behaviour is more optimal on the given terminal.
.SH "RETURN VALUE"
\fBtickit_term_erasech\fP() returns no value.
.SH "SEE ALSO"
.BR tickit_term_build (3),
.BR tickit_term_goto (3),
.BR tickit_term_print (3),
.BR tickit_term_setpen (3),
.BR tickit_term_chpen (3),
.BR tickit_term (7),
.BR tickit (7)
