.TH TICKIT_TERM_CHPEN 3
.SH NAME
tickit_term_chpen, tickit_term_setpen \- set rendering attributes of the terminal
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "void tickit_term_chpen(TickitTerm *" tt ", TickitPen *" pen );
.BI "void tickit_term_setpen(TickitTerm *" tt ", TickitPen *" pen );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_term_chpen\fP() changes the rendering attributes currently in effect in the terminal by setting those attributes specified in the given \fBTickitPen\fP instance. Attributes not present in \fIpen\fP remain unmodified by this operation.
.PP
\fBtickit_term_setpen\fP() changes the rendering attributes currently in effect in the terminal by setting all of the attributes to those given in the \fBTickitPen\fP instance. Any attribute not present in \fIpen\fP is reset back to its default value.
.PP
If the foreground or background colour is set to an index higher than the terminal can support, it will be converted to the best choice that is available from the palette of 8 or 16 colors.
.SH "RETURN VALUE"
\fBtickit_term_chpen\fP() and \fBtickit_term_setpen\fP() return no value.
.SH "SEE ALSO"
.BR tickit_term_build (3),
.BR tickit_term_goto (3),
.BR tickit_term_print (3),
.BR tickit_term (7),
.BR tickit_pen (7),
.BR tickit (7)
