.TH TICKIT_STRINGPOS_ZERO 3
.SH NAME
tickit_stringpos_zero \- clear the fields of a string position counter
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "void tickit_stringpos_zero(TickitStringPos *" pos );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_stringpos_zero\fP() sets the four counter fields of \fIpos\fP to zero. This operation is done implictly by \fBtickit_utf8_count\fP(3), but this function may be useful to initialise a counter to zeros before entering a loop, and using \fBtickit_utf8_countmore\fP(3) for every iteration.
.SH "RETURN VALUE"
\fBtickit_stringpos_zero\fP() returns no value.
.SH "SEE ALSO"
.BR tickit_utf8_count (3),
.BR tickit_stringpos_limit_bytes (3),
.BR tickit (7)
