.TH TICKIT_PEN_BIND_EVENT 3
.SH NAME
tickit_pen_bind_event, tickit_pen_unbind_event_id \- add or remove event handlers
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "typedef int " TickitPenEventFn "(TickitPen *" tt ", TickitEventFlags " flags ,
.BI "    void *" info ", void *" user );
.sp
.BI "int tickit_pen_bind_event(TickitPen *" tt ", TickitPenEvent " ev ,
.BI "    TickitBindFlags " flags ,
.BI "    TickitPenEventFn *" fn ", void *" user );
.BI "void tickit_pen_unbind_event_id(TickitPen *" tt ", int " id );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_pen_bind_event\fP() adds a new event handler to the list of handlers stored by the pen, and returns an integer to identify this handler. This handler will be invoked for occurrences of the event given by the \fIev\fP argument. When invoked, \fIfunc\fP will be passed the pen instance, a flags bitmask, a pointer to an event information structure whose type depends on the event, and the user data pointer it was installed with.
.PP
\fBtickit_pen_unbind_event_id\fP() removes an event handler previously added, by the identifier returned when it was added, invoking it with the \fBTICKIT_EV_UNBIND\fP flag if it was installed with \fBTICKIT_BIND_UNBIND\fP.
.SH "RETURN VALUE"
\fBtickit_pen_bind_event\fP() returns an identifier integer. \fBtickit_pen_unbind_event_id\fP() returns no value.
.SH "SEE ALSO"
.BR tickit_pen_new (3),
.BR tickit_pen (7),
.BR tickit (7)
