.TH TICKIT_TERM_SET_MODE_ALTSCREEN 3
.SH NAME
tickit_term_set_mode_altscreen \- switch the terminal to alternate buffer
.SH SYNOPSIS
.nf
.B #include <tickit.h>
.sp
.BI "void tickit_term_set_mode_altscreen(TickitTerm *" tt ", int " on );
.fi
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_term_set_mode_altscreen\fP() controls the terminal's alternate buffer mode. When this mode is enabled, temporary buffer is used for drawing, preserving the original buffer. This mode is usually used by full-screen applications to preserve the shell's scrollback state.
.SH "RETURN VALUE"
\fBtickit_term_set_mode_altscreen\fP() returns no value.
.SH "SEE ALSO"
.BR tickit_term_new (3),
.BR tickit_term_set_output_fd (3),
.BR tickit_term_set_output_func (3),
.BR tickit_term (7),
.BR tickit (7)
