.TH TICKIT 7
.SH NAME
tickit \- Terminal Interface Construction KIT
.SH DESCRIPTION
\fBtickit\fP is a library for building full-screen interactive programs that use a terminal interface. Typically a program using \fBtickit\fP would consist of an instance of \fBTickitTerm\fP to represent the user's terminal, on which drawing operations are sent and input events are received.
.PP
The application would likely also maintain a \fBTickitRenderBuffer\fP instance into which to draw updates to the screen, before flushing them to the terminal in reaction to user input or other events.
.SH "COMMON TYPES"
Some API functions take or return the following enum type, to represent a tri-state extended boolean concept of true, false, or some third condition typically indicating a "don't care" or "unknown" state; the exact semantics will vary between specific uses and should be documented specifically.
.sp
.EX
.B  typedef enum {
.BR "  TICKIT_YES" " = 1,"
.BR "  TICKIT_NO" " = 0,"
.BR "  TICKIT_MAYBE" " = -1",
.BI "} " TickitMaybeBool ;
.EE
.SH "COMMON EVENTS"
Every object instance that supports events supports the following type of event, in addition to the specific ones listed for that kind of object:
.TP
.B TICKIT_EV_UNBIND
Invoked when the event handler is about to be removed, either because it was unbound individually, or because the object instance itself is being destroyed. This will be the last time the application can use the stored \fIdata\fP argument; it may perform any resource reclaiming operations that are required at this time. The \fIinfo\fP pointer will be \fBNULL\fP.
.SH "SEE ALSO"
.BR tickit_term (7),
.BR tickit_pen (7),
.BR tickit_rect (7),
.BR tickit_rectset (7),
.BR tickit_renderbuffer (7),
.BR tickit_string_count (3)
