.TH TICKIT_TERM_INPUT_WAIT 3
.SH NAME
tickit_term_input_wait, tickit_term_input_wait_msec \- read more data from the terminal
.SH SYNOPSIS
.nf
.B #include <tickit.h>
.sp
.BI "void tickit_term_input_wait(TickitTerm *" tt ", const struct timeval *" timeout );
.BI "void tickit_term_input_wait_msec(TickitTerm *" tt ", long " msec );
.fi
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_term_input_wait\fP() waits for at least one input event to be received, up until the maximum time given. Calling this function may block if the underlying file descriptor is in blocking mode. It may result in \fBTICKIT_EV_KEY\fP or \fBTICKIT_EV_MOUSE\fP events being invoked. If \fItimeout\fP is \fBNULL\fP then no timeout is applied and it will wait indefinitely.
.PP
\fBtickit_term_input_wait_msec\fP() waits as per \fBtickit_term_input_wait\fP() but takes its timeout as an integer specified in miliseconds, or -1 to wait indefinitely with no timeout.
.SH "RETURN VALUE"
\fBtickit_term_input_wait\fP() and \fBtickit_term_input_wait_msec\fP() return no value.
.SH "SEE ALSO"
.BR tickit_term_new (3),
.BR tickit_term_set_input_fd (3),
.BR tickit_term_input_readable (3),
.BR tickit_term_bind_event (3),
.BR tickit_term (7),
.BR tickit (7)
