.TH TICKIT_STRING_MBSWIDTH 3
.SH NAME
tickit_string_mbswidth, tickit_string_byte2col, tickit_string_col2byte \- DEPRECATED
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "int tickit_string_mbswidth(const char *" str );
.sp
.BI "int tickit_string_byte2col(const char *" str ", size_t " byte );
.BI "size_t tickit_string_col2byte(const char *" str ", "int " col );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
These functions are deprecated. Use \fBtickit_utf8_mbswidth\fP(3), \fBtickit_utf8_byte2col\fP(3) or \fBtickit_utf8_col2byte\fP(3) instead.
.SH "SEE ALSO"
.BR tickit_utf8_count (3),
.BR tickit (7)
