.TH TICKIT_RENDERBUFFER_SAVE 3
.SH NAME
tickit_renderbuffer_save, tickit_renderbuffer_restore, tickit_renderbuffer_savepen \- save and restore auxiliary state
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "void tickit_renderbuffer_save(TickitRenderBuffer *" rb );
.BI "void tickit_renderbuffer_restore(TickitRenderBuffer *" rb );
.BI "void tickit_renderbuffer_savepen(TickitRenderBuffer *" rb );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_renderbuffer_save\fP() pushes a new entry to the buffer's saved state stack. This will capture the current values of the auxiliary state, which can be later restored using \fBtickit_renderbuffer_restore\fP().
.PP
\fBtickit_renderbuffer_restore\fP() pops the most recent entry on the buffer's saved state stack and reverts the values of the auxiliary state back to the saved values.
.PP
\fBtickit_renderbuffer_savepen\fP() pushes a new entry to the stack containing just the current pen value. When it is restored, it will only restore the pen; the other attributes will be unaffected.
.SH "AUXILIARY STATE"
The state saved and restored by these functions is:
.IP *
the virtual cursor position
.IP *
the translation offset
.IP *
the clipping rectangle
.IP *
the current pen
.IP *
the set of masked regions
.PP
The pending content is not part of the state stack. It is intended that the state stack be used to help implement recursive drawing operations within the application, by dividing it into separate independent areas; allowing the state to be saved and restored between component parts.
.SH "RETURN VALUE"
None of these functions return a value.
.SH "SEE ALSO"
.BR tickit_renderbuffer_new (3),
.BR tickit_renderbuffer_reset (3),
.BR tickit_renderbuffer (7),
.BR tickit (7)
