.TH TICKIT_SETCTL_INT 3
.SH NAME
tickit_setctl_int\- set an integer toplevel instance control
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "bool tickit_getctl_int(Tickit *" tt ", TickitCtl " ctl ", int *" value );
.BI "bool tickit_setctl_int(Tickit *" tt ", TickitCtl " ctl ", int " value );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_setctl_int\fP() performs a toplevel instance control operation, setting the value of a numeric instance control option. \fBtickit_getctl_int\fP() obtains the value of an instance control setting.
.PP
For the list of possible \fBTickitCtl\fP values and their meanings, see \fBtickit\fP(7).
.SH "RETURN VALUE"
\fBtickit_getctl_int\fP() returns a true value if it recognised the requested control and managed to return the current value of it; false if not. \fBtickit_setctl_int\fP() returns a true value if it recognised the requested control and managed to request the instance to change it; false if not.
.SH "SEE ALSO"
.BR tickit (7)
