.TH TICKIT_RENDERBUFFER_REF 3
.SH NAME
tickit_renderbuffer_ref, tickit_renderbuffer_unref \- adjust the refcount of a render buffer
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "TickitRenderBuffer *tickit_renderbuffer_ref(TickitRenderBuffer *" rb );
.BI "void tickit_renderbuffer_unref(TickitRenderBuffer *" rb );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_renderbuffer_ref\fP() increments the stored refcount of the given render buffer instance by one. It returns the pointer argument itself, so it is useful for chaining.
.PP
\fBtickit_renderbuffer_unref\fP() decrements the stored refcount of the given render buffer instance by one. If the refcount drops to zero, the instance is destroyed. This will release any resources controlled by it and unbind all the bound event handlers, causing \fBTICKIT_EV_UNBIND\fP events if appropriate.
.SH "RETURN VALUE"
\fBtickit_renderbuffer_ref\fP() returns a render buffer instance pointer. \fBtickit_renderbuffer_unref\fP() returns no value.
.SH "SEE ALSO"
.BR tickit_renderbuffer_new (3),
.BR tickit_renderbuffer (7),
.BR tickit (7)
