.TH TICKIT_RENDERBUFFER_TEXT 3
.SH NAME
tickit_renderbuffer_text, tickit_renderbuffer_text_at \- create text regions
.SH SYNOPSIS
.nf
.B #include <tickit.h>
.sp
.BI "int tickit_renderbuffer_text(TickitRenderBuffer *" rb ,
.BI "        char *" text );
.BI "int tickit_renderbuffer_textn(TickitRenderBuffer *" rb ,
.BI "        char *" text ", size_t " len );
.BI "int tickit_renderbuffer_text_at(TickitRenderBuffer *" rb ,
.BI "        int " line ", int " col ", char *" text );
.BI "int tickit_renderbuffer_textn_at(TickitRenderBuffer *" rb ,
.BI "        int " line ", int " col ", char *" text ", size_t " len );
.fi
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_renderbuffer_text\fP() creates a text region that starts at the current virtual cursor position, containing the given text string and set to the current pen. \fBtickit_renderbuffer_textn\fP() creates a text region of at most \fIlen\fP bytes. It returns the number of columns that the text string occupies. This function will update the virtual cursor position.
.PP
\fBtickit_renderbuffer_text_at\fP() creates a text region at the given position. \fBtickit_renderbuffer_textn_at\fP() creates a text region of at most \fIlen\fP bytes. This function does not use or update the virtual cursor position.
.PP
Calls to any of these functions allocate storage owned by the \fITickitRenderBuffer\fP instance itself to store the strings. This storage is only released again by \fBtickit_renderbuffer_reset\fP(3) or by the implicit reset that happens at the end of \fBtickit_renderbuffer_flush_to_term\fP(3).
.SH "RETURN VALUE"
These functions return an integer giving the number of columns the new region occupies.
.SH "SEE ALSO"
.BR tickit_renderbuffer_new (3),
.BR tickit_renderbuffer_blit (3),
.BR tickit_renderbuffer_flush_to_term (3),
.BR tickit_renderbuffer (7),
.BR tickit (7)
