.TH TICKIT_PEN_HAS_ATTR 3
.SH NAME
tickit_pen_has_attr \- test if a pen has a given attribute
.SH SYNOPSIS
.nf
.B #include <tickit.h>
.sp
.BI "int tickit_pen_has_attr(TickitPen *" pen ", TickitPenAttr " attr );
.fi
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_pen_has_attr\fP() tests whether a pen instance has a given attribute defined on it. It returns true if the corresponding \fBtickit_pen_set_*_attr\fP() function has been called since construction, or the last time it was cleared. This is true even if the attribute has been set to its default value.
.SH "RETURN VALUE"
\fBtickit_pen_has_attr\fP() returns a boolean integer.
.SH "SEE ALSO"
.BR tickit_pen_new (3),
.BR tickit_pen_set_bool_attr (3),
.BR tickit_pen_set_int_attr (3),
.BR tickit_pen_set_colour_attr (3),
.BR tickit_pen_clear_attr (3),
.BR tickit_pen (7),
.BR tickit (7)
