.TH TICKIT_RECT 7
.SH NAME
TickitRect \- utility structure representing a rectangular region
.SH SYNOPSIS
.nf
.B #include <tickit.h>
.sp
.BI "typedef struct {"
.BI "  int " top ;
.BI "  int " left ;
.BI "  int " lines ;
.BI "  int " cols ;
.BI "} " TickitRect ;
.fi
.sp
.SH DESCRIPTION
A \fBTickitRect\fP structure represents a single non-empty rectangular region of the screen. It stores the position of the top left corner of the region, and its size in lines and columns.
.SH FUNCTIONS
A new \fBTickitRect\fP structure can be initialised using the \fBtickit_rect_init_sized\fP(3) and \fBtickit_rect_init_bounded\fP(3) functions. Its bottom right corner can be obtained using \fBtickit_rect_bottom\fP(3) and \fBtickit_rect_right\fP(3). Interactions between rectangles can be tested using the predicate functions \fBtickit_rect_contains\fP(3) and \fBtickit_rect_intersects\fP(3). New rectangles can be created from existing ones using \fBtickit_rect_intersect\fP(3) to form the intersection, \fBtickit_rect_add\fP(3) to form the union sum, and \fBtickit_rect_subtract\fP(3).
