.TH TICKIT_STRING_COUNT 3
.SH NAME
tickit_string_count, tickit_string_countmore \- DEPRECATED
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.B  "typedef struct {"
.BI "    size_t " bytes ;
.BI "    int    " codepoints ;
.BI "    int    " graphemes ;
.BI "    int    " columns ;
.BI "} " TickitStringPos ;
.sp
.BI "size_t tickit_string_count(const char *" str ", TickitStringPos *" pos ,
.BI "    const TickitStringPos *" limit );
.BI "size_t tickit_string_countmore(const char *" str ", TickitStringPos *" pos ,
.BI "    const TickitStringPos *" limit );
.sp
.BI "size_t tickit_string_ncount(const char *" str ", size_t " len ,
.BI "    TickitStringPos *" pos ", const TickitStringPos *" limit );
.BI "size_t tickit_string_ncountmore(const char *" str ,
.BI "    TickitStringPos *" pos ", const TickitStringPos *" limit );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
These functions are deprecated. Use the \fBtickit_utf8_count\fP family instead.
.SH "SEE ALSO"
.BR tickit_stringpos_zero (3),
.BR tickit_stringpos_limit_bytes (3),
.BR tickit_utf8_mbswidth (3),
.BR tickit (7)
