.TH TICKIT_RENDERBUFFER_FLUSH_TO_TERM 3
.SH NAME
tickit_renderbuffer_flush_to_term \- output buffer contents to the terminal
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "void tickit_renderbuffer_flush_to_term(TickitRenderBuffer *" rb ", TickitTerm *" tt );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_renderbuffer_flush_to_term\fP() outputs the entire stored state in the buffer to the terminal, then resets the buffer back to its initial state. Stored content is output in a strictly top-to-bottom, left-to-right order, ensuring a minimal amount of cursor movement for efficiency, and helping to reduce output flicker on the terminal display.
.SH "RETURN VALUE"
This function returns nothing.
.SH "SEE ALSO"
.BR tickit_renderbuffer_new (3),
.BR tickit_renderbuffer_reset (3),
.BR tickit_renderbuffer (7),
.BR tickit (7)
