.TH TICKIT_PEN_ATTRNAME 3
.SH NAME
tickit_pen_attrname \- return the name of a pen attribute
.SH SYNOPSIS
.nf
.B #include <tickit.h>
.sp
.BI "const char * tickit_pen_attrname(TickitPenAttr " attr );
.BI "TickitPenAttr tickit_pen_lookup_attr(const char * " name );
.fi
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_pen_attrname\fP() returns the name of the given pen attribute. These names are the lowercase strings given in \fBtickit_pen\fP(7).
.PP
\fBtickit_pen_lookup_attr\fP() returns the attribute constant for a given name. If the name is not recognised then -1 is returned.
.SH "RETURN VALUE"
\fBtickit_pen_attrname\fP() returns a constant string pointer. \fBtickit_pen_lookup_attr\fP() returns an attribute constant or -1.
.SH "SEE ALSO"
.BR tickit_pen (7),
.BR tickit (7)
