.TH TICKIT_RECT_BOTTOM 3
.SH NAME
tickit_rect_bottom, tickit_rect_right \- return the bottom right corner of a rectangle
.SH SYNOPSIS
.nf
.B #include <tickit.h>
.sp
.BI "int tickit_rect_bottom(const TickitRect *" rect );
.BI "int tickit_rect_right(const TickitRect *" rect );
.fi
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_rect_bottom\fP() returns the lower extent of the rectangle; returning the first line past the bottom.
.PP
\fBtickit_rect_right\fP() returns the righthand extent of the rectangle; returning the first column past the righthand edge.
.PP
These functions may be \f(CWstatic inline\fP.
.SH "RETURN VALUE"
\fBtickit_rect_bottom\fP() returns a line number as an integer. \fBtickit_rect_right\fP() returns a column number as an integer.
.SH "SEE ALSO"
.BR tickit_rect_init_sized (3),
.BR tickit_rect_init_bounded (3),
.BR tickit_rect (7),
.BR tickit (7)
