.TH TICKIT_PEN_GET_BOOL_ATTR 3
.SH NAME
tickit_pen_get_bool_attr, tickit_pen_set_bool_attr \- manipulate a boolean pen attribute
.SH SYNOPSIS
.nf
.B #include <tickit.h>
.sp
.BI "bool tickit_pen_get_bool_attr(TickitPen *" pen ", TickitPenAttr " attr );
.BI "void tickit_pen_set_bool_attr(TickitPen *" pen ", TickitPenAttr " attr ", bool " val );
.fi
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_pen_get_bool_attr\fP() returns the current value of the given boolean attribute on the pen, or false if that attribute is not defined.
.PP
\fBtickit_pen_set_bool_attr\fP() provides a new value for the given boolean attribute on the pen. It will invoke the \fBTICKIT_EV_CHANGE\fP event on the pen instance.
.SH "RETURN VALUE"
\fBtickit_pen_get_bool_attr\fP() returns a boolean. \fBtickit_pen_set_bool_attr\fP() returns no value.
.SH "SEE ALSO"
.BR tickit_pen_new (3),
.BR tickit_pen_has_attr (3),
.BR tickit_pen_set_int_attr (3),
.BR tickit_pen_set_colour_attr (3),
.BR tickit_pen_clear_attr (3),
.BR tickit_pen (7),
.BR tickit (7)
