.TH TICKIT_TERM_SET_OUTPUT_BUFFER 3
.SH NAME
tickit_term_set_output_buffer \- define a terminal output buffer
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "void tickit_term_set_output_buffer(TickitTerm *" tt ", size_t " len );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_term_set_output_buffer\fP() sets up an output buffer of the given size, to store output bytes pending being written to the output file descriptor, or using the output function. The value 0 may be given to indicate that no buffer should be used. This buffer is not directly accessible.
.PP
If a buffer is defined, then none of the drawing functions will immediately create output either to the file descriptor or the output function. Instead, they will append into the buffer, to be flushed by calling \fBtickit_term_flush\fP(3). If the buffer fills completely as a result of being written to by a drawing function, it will be flushed to the appropriate output method.
.SH "RETURN VALUE"
\fBtickit_term_set_output_buffer\fP() returns no value.
.SH "SEE ALSO"
.BR tickit_term_build (3),
.BR tickit_term_print (3),
.BR tickit_term_flush (3),
.BR tickit_term (7),
.BR tickit (7)
