.TH TICKIT_RENDERBUFFER_SKIP 3
.SH NAME
tickit_renderbuffer_skip, tickit_renderbuffer_skip_at, tickit_renderbuffer_skip_to \- create skip regions
.SH SYNOPSIS
.nf
.B #include <tickit.h>
.sp
.BI "void tickit_renderbuffer_skip(TickitRenderBuffer *" rb ,
.BI "         int " cols );
.BI "void tickit_renderbuffer_skip_to(TickitRenderBuffer *" rb ,
.BI "         int " col );
.BI "void tickit_renderbuffer_skip_at(TickitRenderBuffer *" rb ,
.BI "         int " line ", int " col ", int " cols );
.fi
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_renderbuffer_skip\fP() creates a skip region that starts at the current virtual cursor position, continuing on for \fIcols\fP cells. \fBtickit_renderbuffer_skip_to\fP() creates a skip region that continues until the given column if the cursor was before that, or has no effect if it was after. Both of these functions will update the virtual cursor position.
.PP
\fBtickit_renderbuffer_skip_at\fP() creates a skip region at the given position and length. This function does not use or update the virtual cursor position.
.SH "RETURN VALUE"
These functions return nothing
.SH "SEE ALSO"
.BR tickit_renderbuffer_new (3),
.BR tickit_renderbuffer_flush_to_term (3),
.BR tickit_renderbuffer (7),
.BR tickit (7)
