.TH TICKIT_PEN_IS_NONEMPTY 3
.SH NAME
tickit_pen_is_nonempty, tickit_pen_is_nondefault \- test if a pen has attributes defined
.SH SYNOPSIS
.nf
.B #include <tickit.h>
.sp
.BI "bool tickit_pen_is_nonempty(TickitPen *" pen );
.BI "bool tickit_pen_is_nondefault(TickitPen *" pen );
.fi
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_pen_is_nonempty\fP() tests whether a pen instance has any attribute defined on it. It returns true even if those attributes take default values.
.PP
\fBtickit_pen_is_nondefault\fP() tests whether a pen instance has any attribute with non-default values defined on it. It false if the pen has no defined attributes, or all of the defined attributes take only the default value for their type.
.SH "RETURN VALUE"
\fBtickit_pen_is_nonempty\fP() and \fBtickit_pen_is_nondefault\fP() return a boolean.
.SH "SEE ALSO"
.BR tickit_pen_new (3),
.BR tickit_pen_set_bool_attr (3),
.BR tickit_pen_set_int_attr (3),
.BR tickit_pen_set_colour_attr (3),
.BR tickit_pen_clear (3),
.BR tickit_pen (7),
.BR tickit (7)
