.TH TICKIT_TERM_FLUSH 3
.SH NAME
tickit_term_flush \- flush the terminal output buffer
.SH SYNOPSIS
.nf
.B #include <tickit.h>
.sp
.BI "void tickit_term_flush(TickitTerm *" tt );
.fi
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_term_flush\fP() flushes any data pending in the output buffer to the terminal, either by calling the output function if defined by \fBtickit_term_set_output_func\fP(3), or by \fBwrite\fP(3) on the output file descriptor defined by \fBtickit_term_set_output_fd\fP(3). If there is no pending data then this function does nothing.
.SH "RETURN VALUE"
\fBtickit_term_flush\fP() returns no value.
.SH "SEE ALSO"
.BR tickit_term_new (3),
.BR tickit_term_set_output_fd (3),
.BR tickit_term_set_output_func (3),
.BR tickit_term_set_output_buffer (3),
.BR tickit_term_print (3),
.BR tickit_term (7),
.BR tickit (7)
