.TH TICKIT_RENDERBUFFER_ERASERECT 3
.SH NAME
tickit_renderbuffer_eraserect, tickit_renderbuffer_clear \- erase large areas
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "void tickit_renderbuffer_eraserect(TickitRenderBuffer *" rb ,
.BI "         TickitRect *" rect );
.BI "void tickit_renderbuffer_clear(TickitRenderBuffer *" rb );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_renderbuffer_eraserect\fP() creates erase regions for every line in \fIrect\fP within the buffer, set to the current pen.
.PP
\fBtickit_renderbuffer_clear\fP() erases the entire buffer area within the current clipping region and masks, setting it all to be erase regions with the curent pen.
.PP
Neither of these functions use or update the virtual cursor.
.SH "RETURN VALUE"
These functions return nothing
.SH "SEE ALSO"
.BR tickit_renderbuffer_new (3),
.BR tickit_renderbuffer_blit (3),
.BR tickit_renderbuffer_flush_to_term (3),
.BR tickit_renderbuffer (7),
.BR tickit (7)
