.TH TICKIT_WINDOW_CLOSE 3
.SH NAME
tickit_window_close \- remove a window from the tree
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "void tickit_window_close(TickitWindow *" win );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_window_close\fP() removes a window from its parent, causing it to no longer affect rendering or recieve input events in any way. After this is done the only operation that is defined any more is \fBtickit_window_unref\fP(3). The window may not be used for further drawing.
.SH "RETURN VALUE"
\fBtickit_window_close\fP() returns no value.
.SH "SEE ALSO"
.BR tickit_window_new (3),
.BR tickit_window_hide (3),
.BR tickit_window (7),
.BR tickit (7)
