.TH TICKIT_RECT_INTERSECTS 3
.SH NAME
tickit_rect_intersects \- test if two rectangles intersect
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "bool tickit_rect_intersects(const TickitRect *" a ", const TickitRect *" b );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_rect_intersects\fP() tests whether the two given rectangles intersect at all. It returns true if there is a non-empty rectangular region in common covered by both rectangles. \fBtickit_rect_intersect\fP(3) can be used to obtain this intersection as well as performing the intersection test itself.
.SH "RETURN VALUE"
\fBtickit_rect_contains\fP() returns a boolean value.
.SH "SEE ALSO"
.BR tickit_rect_init_sized (3),
.BR tickit_rect_init_bounded (3),
.BR tickit_rect_contains (3),
.BR tickit_rect_intersect (3),
.BR tickit_rect (7),
.BR tickit (7)
