.TH TICKIT_CTLNAME 3
.SH NAME
tickit_ctlname \- return the name of a toplevel instance control
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "const char * tickit_ctlname(TickitCtl " ctl );
.BI "TickitCtl tickit_lookup_ctl(const char * " name );
.sp
.BI "TickitCtlType tickit_ctltype(TickitCtl " ctl );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_ctlname\fP() returns the name of the given toplevel instance control. These names are the lowercase strings given in \fBtickit\fP(7).
.PP
\fBtickit_lookup_ctl\fP() returns the control constant for a given name. If the name is not recognised then -1 is returned.
.PP
\fBtickit_ctltype\fP() returns the type of the given instance control, as one of the following constants:
.in
.TP
.B TICKIT_CTLTYPE_BOOL
The value is an integer representing a simple boolean choice, where any nonzero value is true. Use \fPtickit_setctl_int\fP(3) and \fBtickit_getctl_int\fP(3).
.TP
.B TICKIT_CTLTYPE_INT
The value is an integer representing a quantity, or a value in some particular enumeration. Use \fPtickit_setctl_int\fP(3) and \fBtickit_getctl_int\fP(3).
.PP
For unrecognised control types, the function returns 0.
.SH "RETURN VALUE"
\fBtickit_ctlname\fP() returns a constant string pointer. \fBtickit_lookup_ctl\fP() returns an control constant or -1. \fBtickit_ctltype\fP() returns a control type constant or 0.
.SH "SEE ALSO"
.BR tickit (7)
