.TH TICKIT_RECTSET_CLEAR 3
.SH NAME
tickit_rectset_clear \- remove all regions from a rectangle set
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "void tickit_rectset_clear(TickitRectSet *" trs );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_rectset_clear\fP() removes all regions stored by the rectangle set.
.SH "RETURN VALUE"
\fBtickit_rectset_clear\fP() returns no value.
.SH "SEE ALSO"
.BR tickit_rectset_new (3),
.BR tickit_rectset (7),
.BR tickit (7)
