.TH TICKIT_STRING_PUTCHAR 3
.SH NAME
tickit_string_putchar \- DEPRECATED
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "size_t tickit_string_putchar(char *" str ", size_t " len ", long " codepoint );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
This function is deprecated. Use \fBtickit_utf8_put\fP(3) instead.
.SH "SEE ALSO"
.BR tickit_utf8_seqlen (3),
.BR tickit (7)
