.TH TICKIT_PEN_REF 3
.SH NAME
tickit_pen_ref, tickit_pen_unref \- adjust the refcount of a pen
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "TickitPen *tickit_pen_ref(TickitPen *" pen );
.BI "void tickit_pen_unref(TickitPen *" pen );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_pen_ref\fP() increments the stored refcount of the given pen instance by one. It returns the pointer argument itself, so it is useful for chaining.
.PP
\fBtickit_pen_unref\fP() decrements the stored refcount of the given pen instance by one. If the refcount drops to zero, the instance is destroyed as if calling \fBtickit_pen_destroy\fP(3).
.SH "RETURN VALUE"
\fBtickit_pen_ref\fP() returns a pen instance pointer. \fBtickit_pen_unref\fP() returns no value.
.SH "SEE ALSO"
.BR tickit_pen_new (3),
.BR tickit_pen_destroy (3),
.BR tickit_pen (7),
.BR tickit (7)
