.TH TICKIT_STRING_SEQLEN 3
.SH NAME
tickit_string_seqlen \- DEPRECATED
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "int tickit_string_seqlen(long " codepoint );
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
This function is deprecated. Use \fBtickit_utf8_seqlen\fP(3) instead.
.SH "SEE ALSO"
.BR tickit_utf8_put (3),
.BR tickit (7)
