.TH TICKIT_TERM_GOTO 3
.SH NAME
tickit_term_goto, tickit_term_move \- move the terminal output cursor
.SH SYNOPSIS
.nf
.B #include <tickit.h>
.sp
.BI "bool tickit_term_goto(TickitTerm *" tt ", int " line ", int " col );
.BI "void tickit_term_move(TickitTerm *" tt ", int " downward ", int " rightward );
.fi
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_term_goto\fP() moves the terminal output cursor to the absolute position specified. On some terminals, either \fIline\fP or \fIcol\fP may be specified as -1 to move within the line or column it is currently in. Not all terminals may support the partial move ability; so the return value of \fBtickit_term_goto\fP() should be checked after attempting a goto within the line or column to see if it actually worked. If not, the application will have to reset the position using a fully-specified goto.
.PP
\fBtickit_term_move\fP() moves the terminal output cursor relative to its current position. Either \fIdownward\fP or \fIrightward\fP may be specified as 0 to not move in that direction.
.SH "RETURN VALUE"
\fBtickit_term_goto\fP() returns a boolean value indicating whether it was able to support the requested movement. \fBtickit_term_move\fP() returns no value.
.SH "SEE ALSO"
.BR tickit_term_new (3),
.BR tickit_term_print (3),
.BR tickit_term (7),
.BR tickit (7)
