.TH TICKIT_NEW_STDIO 3
.SH NAME
tickit_new_stdio \- create a new toplevel Tickit instance
.SH SYNOPSIS
.EX
.B #include <tickit.h>
.sp
.BI "Tickit *tickit_new_stdio(void);"
.EE
.sp
Link with \fI\-ltickit\fP.
.SH DESCRIPTION
\fBtickit_new_stdio\fP() creates a new toplevel Tickit instance whose terminal is attached to the standard input and output streams.
.PP
The reference count of a newly-constructed toplevel instance will be one. This can be incremented or decremented using \fBtickit_ref\fP(3) and \fBtickit_unref\fP(3). When its reference count reaches zero it is destroyed.
.SH "RETURN VALUE"
If successful, \fBtickit_new_stdio\fP() returns a pointer to the new instance.
.SH "SEE ALSO"
.BR tickit (7)
